import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home({data}) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>hello world</p>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {

  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
